import type { Indicator } from "@/types/indicator-Edpx"

export const indicators: Indicator[] = 
[
  {
    id: "ind-001",
    year: "2567",
    indicatorType: "ตัวชี้วัด EdPEx",
    code: "7.1ก(1)-01 ",
    name: "ร้อยละของบัณฑิตที่ได้งานทำภายใน 1 ปี",
    department: "สำนักงานอธิการบดี",
    owner: "ดร.สมชาย ใจดี",
    dataType: "ร้อยละ",
    targetCondition: "มากกว่าหรือเท่ากับ",
    target: 85,
    unit: "ร้อยละ",
    result: 88.5,
    status: "success",
    collectionPeriod: "รายปี",
    months: ["กันยายน"],
    collectors: [
      { name: "มรภ.อุดรธานี", result: "88.5" },
      { name: "มรภ.สุรินทร์", result: "87.2" },
    ],
  },
  {
    id: "ind-002",
    year: "2567",
    indicatorType: "ตัวชี้วัด EdPEx",
    code: "KPI-2.1",
    name: "จำนวนผลงานวิจัยที่ตีพิมพ์ในระดับนานาชาติ",
    department: "สถาบันวิจัยและพัฒนา",
    owner: "ดร.ประภาส วงศ์เจริญ",
    dataType: "ปริมาณ",
    targetCondition: "มากกว่าหรือเท่ากับ",
    target: 120,
    unit: "เรื่อง",
    result: 98,
    status: "warning",
    collectionPeriod: "รายไตรมาส",
    months: ["มีนาคม"],
    collectors: [{ name: "มรภ.อุดรธานี", result: "98" }],
  },
  {
    id: "ind-003",
    year: "2567",
    indicatorType: "ตัวชี้วัด EdPEx",
    code: "KPI-3.2",
    name: "จำนวนโครงการบริการวิชาการแก่สังคม",
    department: "คณะวิศวกรรมศาสตร์",
    owner: "รศ.ดร.สุดารัตน์ พงษ์ไพบูลย์",
    dataType: "ปริมาณ",
    targetCondition: "มากกว่าหรือเท่ากับ",
    target: 30,
    unit: "โครงการ",
    result: 18,
    status: "danger",
    collectionPeriod: "รายไตรมาส",
    months: ["ธันวาคม"],
    collectors: [{ name: "มรภ.บุรีรัมย์", result: "18" }],
  },
  {
    id: "ind-004",
    year: "2567",
    indicatorType: "ตัวชี้วัด EdPEx",
    code: "KPI-4.1",
    name: "ระดับความพึงพอใจของผู้รับบริการ",
    department: "กองบริหารงานบุคคล",
    owner: "นางวิภาวี สุขสันต์",
    dataType: "ค่าเฉลี่ย",
    targetCondition: "มากกว่าหรือเท่ากับ",
    target: 4.5,
    unit: "คะแนน",
    result: 4.62,
    status: "success",
    collectionPeriod: "รายปี",
    months: ["สิงหาคม"],
    collectors: [{ name: "มหาวิทยาลัยขอนแก่น", result: "4.62" }],
  },
  {
    id: "ind-005",
    year: "2566",
    indicatorType: "ตัวชี้วัด EdPEx",
    code: "KPI-1.2",
    name: "อัตราการคงอยู่ของนักศึกษาชั้นปีที่ 1",
    department: "คณะวิทยาศาสตร์",
    owner: "ผศ.ดร.วิชัย ตั้งมั่น",
    dataType: "ร้อยละ",
    targetCondition: "มากกว่าหรือเท่ากับ",
    target: 90,
    unit: "ร้อยละ",
    result: 91.3,
    status: "success",
    collectionPeriod: "รายปี",
    months: ["มิถุนายน"],
    collectors: [{ name: "UBU", result: "91.3" }],
  },
  {
    id: "ind-006",
    year: "2566",
    indicatorType: "ตัวชี้วัด EdPEx",
    code: "KPI-2.3",
    name: "จำนวนเงินทุนวิจัยจากแหล่งทุนภายนอก",
    department: "สถาบันวิจัยและพัฒนา",
    owner: "ดร.ประภาส วงศ์เจริญ",
    dataType: "ปริมาณ",
    targetCondition: "มากกว่าหรือเท่ากับ",
    target: 50,
    unit: "ล้านบาท",
    result: 42,
    status: "warning",
    collectionPeriod: "รายไตรมาส",
    months: ["มีนาคม", "มิถุนายน", "กันยายน", "ธันวาคม"],
    collectors: [{ name: "มรภ.อุดรธานี", result: "42" }],
  },
  {
    id: "ind-007",
    year: "2567",
    indicatorType: "ด้านทำนุบำรุงศิลปวัฒนธรรม",
    code: "KPI-5.1",
    name: "จำนวนกิจกรรมส่งเสริมศิลปวัฒนธรรม",
    department: "คณะครุศาสตร์",
    owner: "ผศ.มานพ เจริญพร",
    dataType: "ปริมาณ",
    targetCondition: "มากกว่าหรือเท่ากับ",
    target: 12,
    unit: "กิจกรรม",
    result: 14,
    status: "success",
    collectionPeriod: "รายเดือน",
    months: ["กุมภาพันธ์"],
    collectors: [{ name: "มข", result: "14" }],
  },
  {
    id: "ind-008",
    year: "2567",
    indicatorType: "ด้านการบริหารจัดการ",
    code: "KPI-4.3",
    name: "ร้อยละการเบิกจ่ายงบประมาณตามแผน",
    department: "กองนโยบายและแผน",
    owner: "นายกิตติศักดิ์ มั่นคง",
    dataType: "ร้อยละ",
    targetCondition: "มากกว่าหรือเท่ากับ",
    target: 95,
    unit: "ร้อยละ",
    result: 78,
    status: "danger",
    collectionPeriod: "รายไตรมาส",
    months: ["กันยายน"],
    collectors: [{ name: "มรภ.อุดรธานี", result: "78" }],
  },
  {
    id: "ind-009",
    year: "2566",
    indicatorType: "ตัวชี้วัดกลยุทธ์",
    code: "KPI-1.5",
    name: "ร้อยละของอาจารย์ที่มีตำแหน่งทางวิชาการ",
    department: "คณะแพทยศาสตร์",
    owner: "นพ.ธีระพงษ์ แสงทอง",
    dataType: "ร้อยละ",
    targetCondition: "มากกว่าหรือเท่ากับ",
    target: 60,
    unit: "ร้อยละ",
    result: 58,
    status: "warning",
    collectionPeriod: "รายปี",
    months: ["กันยายน"],
    collectors: [{ name: "มรภ.อุดรธานี", result: "58" }],
  },
  {
    id: "ind-010",
    year: "2567",
    indicatorType: "ด้านการบริการวิชาการ",
    code: "KPI-3.4",
    name: "รายได้จากการบริการวิชาการ",
    department: "คณะบริหารธุรกิจ",
    owner: "ดร.อรอุมา ศรีสุข",
    dataType: "ปริมาณ",
    targetCondition: "มากกว่าหรือเท่ากับ",
    target: 10,
    unit: "ล้านบาท",
    result: 12.5,
    status: "success",
    collectionPeriod: "รายไตรมาส",
    months: ["มีนาคม"],
    collectors: [{ name: "มรภ.อุดรธานี", result: "12.5" }],
  },
  {
    id: "ind-011",
    year: "2567",
    indicatorType: "ด้านการบริหารจัดการ",
    code: "KPI-4.5",
    name: "ร้อยละของระบบสารสนเทศที่พร้อมใช้งาน",
    department: "สำนักวิทยบริการและเทคโนโลยีสารสนเทศ",
    owner: "นางสาวพิมพ์ชนก รักเรียน",
    dataType: "ร้อยละ",
    targetCondition: "มากกว่าหรือเท่ากับ",
    target: 99,
    unit: "ร้อยละ",
    result: 99.8,
    status: "success",
    collectionPeriod: "รายเดือน",
    months: ["มกราคม"],
    collectors: [{ name: "มรภ.อุดรธานี", result: "99.8" }],
  },
  {
    id: "ind-012",
    year: "2566",
    indicatorType: "ด้านการวิจัย",
    code: "KPI-2.5",
    name: "จำนวนสิทธิบัตรและอนุสิทธิบัตร",
    department: "คณะวิศวกรรมศาสตร์",
    owner: "รศ.ดร.สุดารัตน์ พงษ์ไพบูลย์",
    dataType: "ปริมาณ",
    targetCondition: "มากกว่าหรือเท่ากับ",
    target: 8,
    unit: "ชิ้น",
    result: 5,
    status: "warning",
    collectionPeriod: "รายปี",
    months: ["ธันวาคม"],
    collectors: [{ name: "มรภ.อุดรธานี", result: "5" }],
  },
]

export function getIndicatorById(id: string): Indicator | undefined {
  return indicators.find((indicator) => indicator.id === id)
}


