import type { Indicator } from "@/types/indicators";

/**
 * Mock indicator dataset.
 *
 * `assignedUserId` is the Row Level Security key — every read MUST be filtered
 * by the logged-in user's id. USER001 owns ids 1-6, USER002 owns ids 7-9.
 */
export const MOCK_INDICATORS: Indicator[] = [
  {
    id: 1,
    assignedUserId: 'USER001',
    dataYear: '2567',
    type: 'EdPEx',
    code: 'KPI-7.1-01',
    name: 'ร้อยละความพึงพอใจของนักศึกษาต่อการจัดการเรียนการสอน',
    department: 'สำนักงานประกันคุณภาพการศึกษา',
    deliveryTime: 'มกราคม',
    collectionPeriod: 'ต.ค. 66 - ธ.ค. 66',
    target: '>= 80.00',
    unit: 'ร้อยละ',
    resultValue: 84.5,
    status: 'completed',
    edpexIndicator: '7.1 ผลลัพธ์ด้านการเรียนรู้ของผู้เรียน',
    strategicIndicator: 'SO1 ยกระดับคุณภาพบัณฑิต',
    okrsIndicator: 'KR1.2 ความพึงพอใจผู้เรียน',
  },
  {
    id: 2,
    assignedUserId: 'USER001',
    dataYear: '2567',
    type: 'กลยุทธ์',
    code: 'KPI-7.2-04',
    name: 'จำนวนผลงานวิจัยที่ได้รับการตีพิมพ์ในระดับนานาชาติ',
    department: 'สำนักงานประกันคุณภาพการศึกษา',
    deliveryTime: 'กุมภาพันธ์',
    collectionPeriod: 'ต.ค. 66 - ม.ค. 67',
    target: '>= 50',
    unit: 'เรื่อง',
    resultValue: null,
    status: 'pending',
    edpexIndicator: '7.2 ผลลัพธ์ด้านการมุ่งเน้นลูกค้า',
    strategicIndicator: 'SO2 เพิ่มผลงานวิจัยคุณภาพสูง',
    okrsIndicator: 'KR2.1 จำนวนผลงานตีพิมพ์',
  },
  {
    id: 3,
    assignedUserId: 'USER001',
    dataYear: '2567',
    type: 'OKRs',
    code: 'KPI-7.3-02',
    name: 'ร้อยละของอาจารย์ที่มีตำแหน่งทางวิชาการ',
    department: 'สำนักงานประกันคุณภาพการศึกษา',
    deliveryTime: 'มีนาคม',
    collectionPeriod: 'ต.ค. 66 - ก.พ. 67',
    target: '>= 60.00',
    unit: 'ร้อยละ',
    resultValue: 52.0,
    status: 'rejected',
    edpexIndicator: '7.3 ผลลัพธ์ด้านบุคลากร',
    strategicIndicator: 'SO3 พัฒนาศักยภาพบุคลากร',
    okrsIndicator: 'KR3.2 สัดส่วนตำแหน่งวิชาการ',
  },
  {
    id: 4,
    assignedUserId: 'USER001',
    dataYear: '2567',
    type: 'EdPEx',
    code: 'KPI-7.4-07',
    name: 'ระดับความสำเร็จของการบริหารความเสี่ยงองค์กร',
    department: 'สำนักงานประกันคุณภาพการศึกษา',
    deliveryTime: 'เมษายน',
    collectionPeriod: 'ต.ค. 66 - มี.ค. 67',
    target: '>= 4.00',
    unit: 'ระดับ',
    resultValue: null,
    status: 'pending',
    edpexIndicator: '7.4 ผลลัพธ์ด้านการนำองค์กรและธรรมาภิบาล',
    strategicIndicator: 'SO4 เสริมสร้างธรรมาภิบาล',
    okrsIndicator: 'KR4.1 ระดับการบริหารความเสี่ยง',
  },
  {
    id: 5,
    assignedUserId: 'USER001',
    dataYear: '2566',
    type: 'กลยุทธ์',
    code: 'KPI-7.5-03',
    name: 'ร้อยละการเบิกจ่ายงบประมาณตามแผน',
    department: 'สำนักงานประกันคุณภาพการศึกษา',
    deliveryTime: 'พฤษภาคม',
    collectionPeriod: 'ต.ค. 65 - เม.ย. 66',
    target: '>= 90.00',
    unit: 'ร้อยละ',
    resultValue: 92.3,
    status: 'completed',
    edpexIndicator: '7.5 ผลลัพธ์ด้านการเงินและตลาด',
    strategicIndicator: 'SO5 บริหารงบประมาณอย่างมีประสิทธิภาพ',
    okrsIndicator: 'KR5.1 อัตราการเบิกจ่าย',
  },
  {
    id: 6,
    assignedUserId: 'USER001',
    dataYear: '2567',
    type: 'OKRs',
    code: 'KPI-7.1-09',
    name: 'จำนวนนักศึกษาที่ได้รับรางวัลระดับชาติและนานาชาติ',
    department: 'สำนักงานประกันคุณภาพการศึกษา',
    deliveryTime: 'มิถุนายน',
    collectionPeriod: 'ต.ค. 66 - พ.ค. 67',
    target: '>= 30',
    unit: 'คน',
    resultValue: null,
    status: 'pending',
    edpexIndicator: '7.1 ผลลัพธ์ด้านการเรียนรู้ของผู้เรียน',
    strategicIndicator: 'SO1 ยกระดับคุณภาพบัณฑิต',
    okrsIndicator: 'KR1.5 รางวัลนักศึกษา',
  },
  {
    id: 7,
    assignedUserId: 'USER002',
    dataYear: '2567',
    type: 'EdPEx',
    code: 'KPI-7.6-01',
    name: 'ร้อยละประสิทธิภาพของกระบวนการทำงานหลัก',
    department: 'กองแผนงานและงบประมาณ',
    deliveryTime: 'มกราคม',
    collectionPeriod: 'ต.ค. 66 - ธ.ค. 66',
    target: '>= 85.00',
    unit: 'ร้อยละ',
    resultValue: 88.0,
    status: 'completed',
    edpexIndicator: '7.6 ผลลัพธ์ด้านประสิทธิผลของกระบวนการ',
    strategicIndicator: 'SO6 ปรับปรุงกระบวนการทำงาน',
    okrsIndicator: 'KR6.1 ประสิทธิภาพกระบวนการ',
  },
  {
    id: 8,
    assignedUserId: 'USER002',
    dataYear: '2567',
    type: 'กลยุทธ์',
    code: 'KPI-7.3-05',
    name: 'ร้อยละความผูกพันของบุคลากรต่อองค์กร',
    department: 'กองแผนงานและงบประมาณ',
    deliveryTime: 'กุมภาพันธ์',
    collectionPeriod: 'ต.ค. 66 - ม.ค. 67',
    target: '>= 75.00',
    unit: 'ร้อยละ',
    resultValue: null,
    status: 'pending',
    edpexIndicator: '7.3 ผลลัพธ์ด้านบุคลากร',
    strategicIndicator: 'SO3 พัฒนาศักยภาพบุคลากร',
    okrsIndicator: 'KR3.4 ความผูกพันบุคลากร',
  },
  {
    id: 9,
    assignedUserId: 'USER002',
    dataYear: '2566',
    type: 'OKRs',
    code: 'KPI-7.5-08',
    name: 'รายได้จากการบริการวิชาการ',
    department: 'กองแผนงานและงบประมาณ',
    deliveryTime: 'มีนาคม',
    collectionPeriod: 'ต.ค. 65 - ก.พ. 66',
    target: '>= 10',
    unit: 'ล้านบาท',
    resultValue: 12.4,
    status: 'completed',
    edpexIndicator: '7.5 ผลลัพธ์ด้านการเงินและตลาด',
    strategicIndicator: 'SO5 บริหารงบประมาณอย่างมีประสิทธิภาพ',
    okrsIndicator: 'KR5.3 รายได้บริการวิชาการ',
  },
]
