import type { User } from '@/types/user'

export const mockUsers: User[] = [
  {
    id: 1,
    username: 'AdminDEMO',
    fullname: 'Admin DEMO',
    email: 'admindemo@gmail.com',
    department: 'ไม่มี',
    phone: '02345678999',
    role: 'ADMIN',
  },
  {
    id: 2,
    username: 'somchai.j',
    fullname: 'สมชาย ใจดี',
    email: 'somchai.j@edpex.ac.th',
    department: 'คณะวิศวกรรมศาสตร์',
    phone: '0812345678',
    role: 'EXECUTIVE',
  },
  {
    id: 3,
    username: 'wipada.s',
    fullname: 'วิภาดา สุขสันต์',
    email: 'wipada.s@edpex.ac.th',
    department: 'คณะวิทยาศาสตร์',
    phone: '0898765432',
    role: 'USER',
  },
  {
    id: 4,
    username: 'narong.t',
    fullname: 'ณรงค์ ตั้งมั่น',
    email: 'narong.t@edpex.ac.th',
    department: 'กองนโยบายและแผน',
    phone: '0823456789',
    role: 'USER',
  },
  {
    id: 5,
    username: 'pranee.k',
    fullname: 'ปราณี คงทน',
    email: 'pranee.k@edpex.ac.th',
    department: 'คณะแพทยศาสตร์',
    phone: '0867891234',
    role: 'EXECUTIVE',
  },
  {
    id: 6,
    username: 'thanakorn.p',
    fullname: 'ธนกร พัฒนา',
    email: 'thanakorn.p@edpex.ac.th',
    department: 'สำนักวิทยบริการและเทคโนโลยีสารสนเทศ',
    phone: '0845678912',
    role: 'USER',
  },
  {
    id: 7,
    username: 'sukanya.m',
    fullname: 'สุกัญญา มีสุข',
    email: 'sukanya.m@edpex.ac.th',
    department: 'คณะบริหารธุรกิจ',
    phone: '0876543210',
    role: 'USER',
  },
  {
    id: 8,
    username: 'apichat.r',
    fullname: 'อภิชาติ รุ่งเรือง',
    email: 'apichat.r@edpex.ac.th',
    department: 'สำนักงานอธิการบดี',
    phone: '0834567891',
    role: 'EXECUTIVE',
  },
  {
    id: 9,
    username: 'kanya.w',
    fullname: 'กัญญา วงศ์ไทย',
    email: 'kanya.w@edpex.ac.th',
    department: 'คณะวิทยาศาสตร์',
    phone: '0856789123',
    role: 'USER',
  },
  {
    id: 10,
    username: 'decha.s',
    fullname: 'เดชา สมบูรณ์',
    email: 'decha.s@edpex.ac.th',
    department: 'คณะวิศวกรรมศาสตร์',
    phone: '0889123456',
    role: 'USER',
  },
  {
    id: 11,
    username: 'malee.c',
    fullname: 'มาลี ชื่นบาน',
    email: 'malee.c@edpex.ac.th',
    department: 'กองนโยบายและแผน',
    phone: '0812378945',
    role: 'USER',
  },
  {
    id: 12,
    username: 'surasak.b',
    fullname: 'สุรศักดิ์ บุญมี',
    email: 'surasak.b@edpex.ac.th',
    department: 'คณะแพทยศาสตร์',
    phone: '0823498761',
    role: 'EXECUTIVE',
  },
]
